### ISSUE TITLE
Issue on building

### ISSUE THREAD

**Issue by tangible-idea** [Nikolaiko/DrawOnImagePlugin#1]
FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Build file '/Users/mark/Documents/Source/DrawOnImagePlugin/android/build.gradle' line: 38
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':draw_on_image_plugin'.
[        ] > Cannot convert a null value to an object of type Dependency.
[        ]   The following types/formats are supported:
[        ]     - Instances of Dependency.
[        ]     - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
[        ]     - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
[        ]     - FileCollections, for example files('some.jar', 'someOther.jar').
[        ]     - Projects, for example project(':some:project:path').
[        ]     - ClassPathNotation, for example gradleApi().

I had an error on building the project while I was using in my project and building the example itself either.
On line 38 in build.gradle is:  `compileOnly rootProject.findProject(":path_provider")` 
What am I missing?

**Comment by Nikolaiko** [comment]
Hi, thanks for creating an issue I will take a look.

**Comment by Nikolaiko** [comment]
@tangible-idea I removed path_provider from plugin. And updated plugin to v1.0.0 tested with example app. It's working now.

**Comment by Nikolaiko** [comment]
Closing as solved and no response from reporter.
